kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-bootcamp-ts1
  labels:
    app: openshift-bootcamp-ts1
spec:
  selector:
    matchLabels:
      app: openshift-bootcamp-ts1
  template:
    metadata:
      labels:
        app: openshift-bootcamp-ts1
    spec:
      containers:
        - name: cli
          image: 'image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli:dne'
