kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-bootcamp-ts2
  labels:
    app: openshift-bootcamp-ts2
spec:
  selector:
    matchLabels:
      app: openshift-bootcamp-ts2
  template:
    metadata:
      labels:
        app: openshift-bootcamp-ts2
    spec:
      containers:
        - name: cli
          image: 'arwthomasm/private:latest-pacman'
