kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-bootcamp-ts4
  labels:
    app: openshift-bootcamp-ts4
spec:
  selector:
    matchLabels:
      app: openshift-bootcamp-ts4
  template:
    metadata:
      labels:
        app: openshift-bootcamp-ts4
    spec:
      containers:
        - name: cli
          image: 'image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli'
          command: ["sleep", "9999"]
          resources:
            requests:
              cpu: "100"
              memory: "500Gi"
