kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-bootcamp-ts5
  labels:
    app: openshift-bootcamp-ts5
spec:
  selector:
    matchLabels:
      app: openshift-bootcamp-ts5
  template:
    metadata:
      labels:
        app: openshift-bootcamp-ts5
    spec:
      containers:
        - name: cli
          image: 'image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli'
          command: ["sleep", "9999"]
          envFrom:
            - configMapRef:
                name: does-not-exist
