kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-bootcamp-ts7
  labels:
    app: openshift-bootcamp-ts7
spec:
  selector:
    matchLabels:
      app: openshift-bootcamp-ts7
  template:
    metadata:
      labels:
        app: openshift-bootcamp-ts7
    spec:
      containers:
        - name: cli
          image: 'image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli'
          command: ["sleep", "9999"]
          securityContext:
            privileged: true