kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-bootcamp-ts8
  labels:
    app: openshift-bootcamp-ts8
spec:
  selector:
    matchLabels:
      app: openshift-bootcamp-ts8
  template:
    metadata:
      labels:
        app: openshift-bootcamp-ts8
    spec:
      containers:
        - name: nginx
          image: 'quay.io/thomas_marko/nginx'
          readinessProbe:
            httpGet:
              path: /nonexistent
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
